name: Run cowsay script

on: push

jobs:
  script_job: 
     runs-on: ubuntu-latest
     steps: 
       - name: execute shell script
         run: |
           chmod +x ./ascii.sh
           ./ascii.sh
