name: Hello world 

on: workflow_run

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello world 
        run: 'echo "Hello world"'

      - name: checkout Repo
        uses: actions/checkout@v4

      - name: build docker image
        run: |
           ls -al
           docker build . -f Dockerfile 
