
name: Multi-line commands/ third party libraries

on: workflow_run

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: list files and read files
        run: |
           ls -al
           cat Dockerfile

      - name: Generate ASCII artwork
        run: |
           sudo apt install cowsay
           cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
          
