name: Hello World

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hello world
        run: |
          'echo "Hello world job 2"
           ls -al
           cat Dockerfile

      - name: Generate ASCII artwork
        run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
          
